name: "GoReleaser"
version: "0.1.0"
description: "Adds a GoReleaser config and GitHub Actions release workflow"
variables:
  name:
    prompt: "Project name:"
    required: true
    default: "$output"
  owner:
    prompt: "Owner:"
    help: "Organization or username"
    required: true
    default: "$username"
  gitserver:
    prompt: "Git Server:"
    default: "github.com"
  sbom:
    confirm: true
    prompt: "Generate SBOM artifacts?"
