---
if: ci && ci_type == "Drone"
---
---
kind: pipeline
type: docker
name: backend

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: build
    image: golang:1.23
    volumes:
      - name: deps
        path: /go
    commands:
      - make

  - name: linter
    image: golang:1.23
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
      - ./bin/golangci-lint run --timeout 5m
      - rm -r ./bin/

volumes:
  - name: deps
    host:
      path: /var/lib/cache/godeps/
