name: "Go Project Template"
version: "0.1.0"
description: "Generates a simple Go project"
delimiters: ["{{", "}}"]
variables:
  name:
    prompt: "Name:"
    help: "Project's name"
    required: true
  owner:
    prompt: "Owner:"
    help: "Organization or username"
    required: true
  gitserver:
    prompt: "Git Server:"
    default: "github.com"
    help: "Git server, used for import path and module declaration"
  description:
    prompt: "Project's description:"
    required: true
    default: "Simple go project"
  gin:
    confirm: true
    prompt: "Add gin router?"
    variables:
      otel:
        confirm: true
        prompt: "Add OpenTelemetry instrumentation? (traces + metrics + logs via OTLP)"
  conf:
    confirm: true
    prompt: "Generate base config file?"
  docker:
    confirm: true
    prompt: "Add Dockerfile and dockerignore?"
  goreleaser:
    confirm: true
    prompt: "Enable goreleaser?"

includes:
  - source: ../common/license
    confirm: true
    prompt: "Add a LICENSE file?"
  - source: ../common/ci
    confirm: true
    prompt: "Add CI workflow?"
  - source: ../common/renovate
    confirm: true
    prompt: "Add Renovate config?"
  - source: ../common/goreleaser
    if: goreleaser
