name: "Go PocketBase Template"
version: "0.1.0"
description: "Generates a Go project using PocketBase as the backend framework"
delimiters: ["{{", "}}"]
variables:
  name:
    prompt: "Name:"
    help: "Project's name"
    required: true
  owner:
    prompt: "Owner:"
    help: "Organization or username"
    required: true
  gitserver:
    prompt: "Git Server:"
    default: "github.com"
    help: "Git server, used for import path and module declaration"
  description:
    prompt: "Project's description:"
    required: true
    default: "PocketBase backend project"
  license:
    values: ["MIT", "Apache License 2.0", "GPL", "LGPL", "WTFPL", ""]
    default: "MIT"
    help: "License to be applied to the project. Select the last option if you don't want a license."
    prompt: "License"
  docker:
    confirm: true
    prompt: "Add Dockerfile and dockerignore?"
  renovate:
    confirm: true
    prompt: "Add renovate config?"
  ci:
    confirm: true
    prompt: "Add CI config?"
  goreleaser:
    confirm: true
    prompt: "Enable goreleaser?"
  year:
    prompt: "Copyright year:"
    default: "2026"
    help: "Year for copyright notices in LICENSE"
